# Generated by Django 3.1.7 on 2022-02-06 12:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220129_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='verification',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.auth_upload_to),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
