# Generated by Django 3.1.7 on 2022-03-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noti',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
