export const authConstants = {
    LOGIN: 'LOGIN',
    USER_LOADED: 'USER_LOADED',
    AUTHENTICATED: 'AUTHENTICATED',
    REFRESH: 'REFRESH',
    ACCOUNT_EDIT: 'ACCOUNT_EDIT',
    PASSWORD_SET: 'PASSWORD_SET',
    PASSWORD_RESET: 'PASSWORD_RESET',
    PASSWORD_RESET_CONFIRM: 'PASSWORD_RESET_CONFIRM',
    SIGNUP: 'SIGNUP',
    ACTIVATION: 'ACTIVATION',
    RESEND_ACTIVATION: 'RESEND_ACTIVATION',
    LOGOUT: 'LOGOUT',
    USER_DELETE: 'USER_DELETE'
}

export const userConstants = {
    GET_REALTIME_USER: 'GET_REALTIME_USER',
    GET_REALTIME_USERS: 'GET_REALTIME_USERS',
    GET_ID_CHECK: 'GET_ID_CHECK',
    GET_CONVERSATIONS: 'GET_CONVERSATIONS',
    GET_REALTIME_MESSAGES: 'GET_REALTIME_MESSAGES',
    GET_REALTIME_LISTS: 'GET_REALTIME_LISTS',
    LOGOUT_CHAT: 'LOGOUT_CHAT',
    EXIT_CHAT: 'EXIT_CHAT',
    GET_POST_USER: 'GET_POST_USER',
    USER_BLOCK: 'USER_BLOCK',
    USER_UNBLOCK: 'USER_UNBLOCK'
}

export const postConstants = {
    GET_DETAIL: 'GET_DETAIL',
    UPDATE: 'UPDATE',
    REMOVE: 'REMOVE',
    READ: 'READ',
    CREATE: 'CREATE',
    FINISH: 'FINISH',
    LOGOUT_POST: 'LOGOUT_POST'
}