# Generated by Django 3.1.7 on 2021-12-23 04:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('mbti', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('option', models.BooleanField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
