# Generated by Django 3.1.7 on 2022-01-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='mbti',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
