# Generated by Django 3.1.7 on 2022-02-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20220121_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
