# Generated by Django 3.1.7 on 2022-02-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_info_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.TextField(),
        ),
    ]
